config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/administrator', as: 'rails_admin'
  resources :teches
  resources :sports
  resources :minions
  resources :foods
  # get 'admin/index'
  # get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users

  get 'admin' => 'admin#index'
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end
  root 'admin#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tech.rb
class Tech < ApplicationRecord
end

app/controllers/teches_controller.rb
class TechesController < ApplicationController
  before_action :set_tech, only: [:show, :edit, :update, :destroy]

  # GET /teches
  # GET /teches.json
  def index
    @teches = Tech.all
  end

  # GET /teches/1
  # GET /teches/1.json
  
  # GET /teches/new
  def new
    @tech = Tech.new
  end

  def show
  end

  # GET /teches/1/edit
  def edit
  end

  # POST /teches
  # POST /teches.json
  def create
    @tech = Tech.new(tech_params)

    respond_to do |format|
      if @tech.save
        format.html { redirect_to @tech, notice: 'Tech was successfully created.' }
        format.json { render :show, status: :created, location: @tech }
      else
        format.html { render :new }
        format.json { render json: @tech.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teches/1
  # PATCH/PUT /teches/1.json
  def update
    respond_to do |format|
      if @tech.update(tech_params)
        format.html { redirect_to @tech, notice: 'Tech was successfully updated.' }
        format.json { render :show, status: :ok, location: @tech }
      else
        format.html { render :edit }
        format.json { render json: @tech.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teches/1
  # DELETE /teches/1.json
  def destroy
    @tech.destroy
    respond_to do |format|
      format.html { redirect_to teches_url, notice: 'Tech was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tech
       @tech = Tech.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tech_params
      params.require(:tech).permit(:question, :option1, :option2, :option3, :option4, :ans)
    end
end

app/helpers/teches_helper.rb
module TechesHelper
end

app/views/teches/_form.html.erb
<%= form_with(model: tech, local: true) do |form| %>
  <% if tech.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tech.errors.count, "error") %> prohibited this tech from being saved:</h2>

      <ul>
      <% tech.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :tech_question %>
  </div>

  <div class="field">
    <%= form.label :option1 %>
    <%= form.text_field :option1, id: :tech_option1 %>
  </div>

  <div class="field">
    <%= form.label :option2 %>
    <%= form.text_field :option2, id: :tech_option2 %>
  </div>

  <div class="field">
    <%= form.label :option3 %>
    <%= form.text_field :option3, id: :tech_option3 %>
  </div>

  <div class="field">
    <%= form.label :option4 %>
    <%= form.text_field :option4, id: :tech_option4 %>
  </div>

  <div class="field">
    <%= form.label :ans %>
    <%= form.number_field :ans, id: :tech_ans %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teches/edit.html.erb
<h1>Editing Tech</h1>

<%= render 'form', tech: @tech %>

<%= link_to 'Show', @tech %> |
<%= link_to 'Back', teches_path %>

app/views/teches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teches</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Option1</th>
      <th>Option2</th>
      <th>Option3</th>
      <th>Option4</th>
      <th>Ans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teches.each do |tech| %>
      <tr>
        <td><%= tech.question %></td>
        <td><%= tech.option1 %></td>
        <td><%= tech.option2 %></td>
        <td><%= tech.option3 %></td>
        <td><%= tech.option4 %></td>
        <td><%= tech.ans %></td>
        <td><%= link_to 'Show', tech %></td>
        <td><%= link_to 'Edit', edit_tech_path(tech) %></td>
        <td><%= link_to 'Destroy', tech, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tech', new_tech_path %>

app/views/teches/new.html.erb
<h1>New Tech</h1>

<%= render 'form', tech: @tech %>

<%= link_to 'Back', teches_path %>

app/views/teches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @tech.question %>
</p>

<p>
  <strong>Option1:</strong>
  <%= @tech.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @tech.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @tech.option3 %>
</p>

<p>
  <strong>Option4:</strong>
  <%= @tech.option4 %>
</p>

<p>
  <strong>Ans:</strong>
  <%= @tech.ans %>
</p>

<%= link_to 'Edit', edit_tech_path(@tech) %> |
<%= link_to 'Back', teches_path %>