config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/administrator', as: 'rails_admin'
  resources :teches
  resources :sports
  resources :minions
  resources :foods
  # get 'admin/index'
  # get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :users

  get 'admin' => 'admin#index'
  controller :sessions do
  	get 'login' => :new
  	post 'login' => :create
  	delete 'logout' => :destroy
  end
  root 'admin#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/minion.rb
class Minion < ApplicationRecord
end

app/controllers/minions_controller.rb
class MinionsController < ApplicationController
  before_action :set_minion, only: [:show, :edit, :update, :destroy]

  # GET /minions
  # GET /minions.json
  def index
    @minions = Minion.all
  end

  # GET /minions/1
  # GET /minions/1.json
  def show
  end

  # GET /minions/new
  def new
    @minion = Minion.new
  end

  # GET /minions/1/edit
  def edit
  end

  # POST /minions
  # POST /minions.json
  def create
    @minion = Minion.new(minion_params)

    respond_to do |format|
      if @minion.save
        format.html { redirect_to @minion, notice: 'Minion was successfully created.' }
        format.json { render :show, status: :created, location: @minion }
      else
        format.html { render :new }
        format.json { render json: @minion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /minions/1
  # PATCH/PUT /minions/1.json
  def update
    respond_to do |format|
      if @minion.update(minion_params)
        format.html { redirect_to @minion, notice: 'Minion was successfully updated.' }
        format.json { render :show, status: :ok, location: @minion }
      else
        format.html { render :edit }
        format.json { render json: @minion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /minions/1
  # DELETE /minions/1.json
  def destroy
    @minion.destroy
    respond_to do |format|
      format.html { redirect_to minions_url, notice: 'Minion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_minion
      @minion = Minion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def minion_params
      params.require(:minion).permit(:question, :option1, :option2, :option3, :option4, :ans)
    end
end

app/helpers/minions_helper.rb
module MinionsHelper
end

app/views/minions/_form.html.erb
<%= form_with(model: minion, local: true) do |form| %>
  <% if minion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(minion.errors.count, "error") %> prohibited this minion from being saved:</h2>

      <ul>
      <% minion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question, id: :minion_question %>
  </div>

  <div class="field">
    <%= form.label :option1 %>
    <%= form.text_field :option1, id: :minion_option1 %>
  </div>

  <div class="field">
    <%= form.label :option2 %>
    <%= form.text_field :option2, id: :minion_option2 %>
  </div>

  <div class="field">
    <%= form.label :option3 %>
    <%= form.text_field :option3, id: :minion_option3 %>
  </div>

  <div class="field">
    <%= form.label :option4 %>
    <%= form.text_field :option4, id: :minion_option4 %>
  </div>

  <div class="field">
    <%= form.label :ans %>
    <%= form.number_field :ans, id: :minion_ans %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/minions/edit.html.erb
<h1>Editing Minion</h1>

<%= render 'form', minion: @minion %>

<%= link_to 'Show', @minion %> |
<%= link_to 'Back', minions_path %>

app/views/minions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Minions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Option1</th>
      <th>Option2</th>
      <th>Option3</th>
      <th>Option4</th>
      <th>Ans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @minions.each do |minion| %>
      <tr>
        <td><%= minion.question %></td>
        <td><%= minion.option1 %></td>
        <td><%= minion.option2 %></td>
        <td><%= minion.option3 %></td>
        <td><%= minion.option4 %></td>
        <td><%= minion.ans %></td>
        <td><%= link_to 'Show', minion %></td>
        <td><%= link_to 'Edit', edit_minion_path(minion) %></td>
        <td><%= link_to 'Destroy', minion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Minion', new_minion_path %>

app/views/minions/new.html.erb
<h1>New Minion</h1>

<%= render 'form', minion: @minion %>

<%= link_to 'Back', minions_path %>

app/views/minions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @minion.question %>
</p>

<p>
  <strong>Option1:</strong>
  <%= @minion.option1 %>
</p>

<p>
  <strong>Option2:</strong>
  <%= @minion.option2 %>
</p>

<p>
  <strong>Option3:</strong>
  <%= @minion.option3 %>
</p>

<p>
  <strong>Option4:</strong>
  <%= @minion.option4 %>
</p>

<p>
  <strong>Ans:</strong>
  <%= @minion.ans %>
</p>

<%= link_to 'Edit', edit_minion_path(@minion) %> |
<%= link_to 'Back', minions_path %>